{"name": "TC010_Login with invalid credentials", "status": "passed", "description": "D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\test_cases\\..\\features\\sauce_demo.feature: TC010_Login with invalid credentials", "steps": [{"name": "Login into sauce demo using id and password", "status": "passed", "start": 1723446812932, "stop": 1723446813180}, {"name": "Click login button", "status": "passed", "start": 1723446816182, "stop": 1723446816248}, {"name": "Get error message after login failure", "status": "passed", "start": 1723446819252, "stop": 1723446819280}], "attachments": [{"name": "log", "source": "7d266f34-7223-4bbf-9df8-42747a9a9846-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "42f8e170-3f89-44a4-805a-fdbd16205456-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "_pytest_bdd_example", "value": "{'username': 'standard_user', 'pwd': 'U0g3UlNLNkZXTkZDTEREUEVDUUJPNVpDNEk='}"}], "start": 1723446802927, "stop": 1723446819280, "uuid": "1c73e8df-033b-447d-ad6a-7e5cf5f902d0", "historyId": "67334d44a5552305012f5847043e852b", "testCaseId": "f376bf8030f727c3a79ad66993d326d4", "fullName": "tests.test_cases.test_saucedemo#test_report_tc10", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Validate Login Credentials"}, {"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "tests.test_cases"}, {"name": "suite", "value": "test_saucedemo"}, {"name": "host", "value": "TIGER04836"}, {"name": "thread", "value": "24268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases.test_saucedemo"}]}